// The fun and easy project “Guess the Number” is a short Java project that allows the user to
//  guess the number generated by the computer & involves the following steps:
//  1.The system generates a random number from a given range, say 1 to 100.
//  2.The user is prompted to enter their given number in a displayed dialogue box.
//  3.The computer then tells if the entered number matches the guesses number or it is
//  higher/lower than the generated number.
//  4.The game continues under the user guessing the number.
//  You can also incorporate further details as:
//  Limiting the number of attempts.
//  Adding more rounds.
//  Displaying score.
//  Giving points based on the number of attempts.



import java.util.Random;
import java.util.Scanner;


class Game {
    public int number;
    public int noOfguess = 0;
    public int inputNumber;

    
    Game() {
        Random rand = new Random();
        this.number = rand.nextInt(100);
    }


    void takeUserInput() {
        
        System.out.print("Enter your guess: ");
        Scanner sc = new Scanner(System.in);
        inputNumber = sc.nextInt();
    }

    // Method to check if the number is correct
    boolean isCorrectNumber() {
        noOfguess++;
        if (inputNumber == number) {
            
            System.out.println("*******************************************");
            System.out.format("CORRECT! You guessed the number %d! \n", number);
            System.out.format("   You took %d attempts.\n", noOfguess);
            System.out.println("*******************************************");
            return true;
        } else if (inputNumber > number) {
            System.out.println("Your guess is too HIGH...");
        } else if (inputNumber < number) {
            System.out.println("Your guess is too LOW....");
        }
        return false;
    }
}


public class Guess_Number {
    public static void main(String[] args) {

        
        System.out.println("-------------------------------------------");
        System.out.println("--- Welcome to the Guess the Number Game! ---");
        System.out.println("-------------------------------------------");

        Game g = new Game();
        boolean hasWon = false;
        int maxAttempts = 10;

        
        System.out.println("I have selected a number between 0 and 99.");
        System.out.println("You have " + maxAttempts + " attempts to guess it. Good luck!");

        
        while (!hasWon && g.noOfguess < maxAttempts) {
            // --- Attempt Counter ---
            System.out.println("\n----- Attempt #" + (g.noOfguess + 1) + " -----");
            g.takeUserInput();
            hasWon = g.isCorrectNumber();
        }

        
        if (!hasWon) {
            System.out.println("\n-------------------------------------------");
            System.out.println("              GAME OVER!              ");
            System.out.println("   You've used all your attempts.");
            System.out.println("   The correct number was: " + g.number);
            System.out.println("-------------------------------------------");
        }
    }
}